# Generated by Django 4.1.7 on 2023-04-21 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='service_images')),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Works', models.CharField(max_length=256)),
                ('WorksDescription', models.CharField(max_length=5000)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_workDescriptions', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=256)),
                ('plan_cost_mini', models.DecimalField(decimal_places=2, max_digits=256)),
                ('plan_cost_pro', models.DecimalField(decimal_places=2, max_digits=256)),
                ('plan_cost_master', models.DecimalField(decimal_places=2, max_digits=256)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_plans', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=256)),
                ('plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_services', to='services.plans')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_plan', to='services.service')),
            ],
        ),
    ]
