# Generated by Django 4.1.7 on 2023-04-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=5000)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_planDescriptions', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=256)),
                ('plan_cost', models.DecimalField(decimal_places=2, max_digits=256)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_plan', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='AboutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('step_1', models.CharField(max_length=5000)),
                ('step_2', models.CharField(max_length=5000)),
                ('step_3', models.CharField(max_length=5000)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_about', to='services.service')),
            ],
        ),
    ]
