# Generated by Django 4.1.7 on 2023-04-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='picture', upload_to='service_images'),
            preserve_default=False,
        ),
    ]
