# Generated by Django 4.1.7 on 2023-04-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='service_images')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_services', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='MiniServiceWorkDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Works', models.CharField(max_length=256)),
                ('WorksDescription', models.CharField(max_length=5000)),
                ('mini_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_service_work', to='services.miniservices')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='examples')),
                ('mini_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_examples', to='services.miniservices')),
            ],
        ),
    ]
