# Generated by Django 4.1.7 on 2023-04-18 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandescriptions',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_services', to='services.plan'),
        ),
    ]
